# Generated by Django 5.0.2 on 2024-09-01 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now=True)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=300)),
                ('total_pedido', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('pedido', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='productos.productos')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos_pedido',
            field=models.ManyToManyField(through='pedidos.ProductoPedido', to='productos.productos'),
        ),
    ]
