# Generated by Django 5.0.2 on 2024-09-02 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_pedido_pedidos'),
        ('productos', '0002_remove_productos_imagen_alter_productos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos_pedido_set', to='pedidos.pedidos'),
        ),
        migrations.AlterField(
            model_name='productopedido',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pedidos_producto', to='productos.productos'),
        ),
    ]
