# Generated by Django 5.0.2 on 2024-09-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_productopedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='total_pedido',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productopedido',
            name='cantidad_producto',
            field=models.IntegerField(default=0),
        ),
    ]
