# Generated by Django 5.0.2 on 2024-09-05 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedidos_total_pedido_and_more'),
        ('productos', '0002_remove_productos_imagen_alter_productos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopedido',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pedidos_producto', to='productos.productos'),
        ),
    ]
