# Generated by Django 5.0.2 on 2024-09-01 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('categoria', models.ForeignKey(default='Sin categoria', on_delete=django.db.models.deletion.SET_DEFAULT, to='productos.categorias')),
            ],
        ),
    ]
