# Generated by Django 5.0.2 on 2024-09-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
        ),
    ]
